# Generated by Django 4.1.1 on 2022-11-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(
                    blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('is_retail', models.BooleanField(
                    blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetailItem',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='warehouse_admin.itemtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RetailCard',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conversion_date', models.DateField(auto_now_add=True)),
                ('weight', models.IntegerField()),
                ('type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='warehouse_admin.itemtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCard',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[
                 ('Good', 'Good'), ('Damaged', 'Damaged'), ('Frozen', 'Frozen')], default='Good', max_length=10)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('receiving_date', models.DateField(auto_now_add=True)),
                ('received_from', models.CharField(
                    default='Yemen', max_length=50)),
                ('is_transforming', models.BooleanField(
                    blank=True, default=False, null=True)),
                ('is_priced', models.BooleanField(
                    blank=True, default=False, null=True)),
                ('batch', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='warehouse_admin.batch')),
                ('stock', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='warehouse_admin.stock')),
                ('type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='warehouse_admin.itemtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsMovement',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='warehouse_admin.itemcard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
