# Generated by Django 4.1.1 on 2022-11-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcard',
            name='receiving_date',
        ),
        migrations.RemoveField(
            model_name='retailcard',
            name='conversion_date',
        ),
    ]
