# Generated by Django 4.1.1 on 2022-11-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_admin', '0003_alter_batch_quantity_alter_itemcard_is_priced_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
