# Generated by Django 4.1.1 on 2022-11-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_admin', '0004_alter_itemtype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsmovement',
            name='date',
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='is_retail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
