# Generated by Django 4.1.1 on 2022-11-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_admin', '0006_alter_batch_code_alter_batch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmovement',
            name='batch',
            field=models.CharField(default='-', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsmovement',
            name='code',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsmovement',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsmovement',
            name='status',
            field=models.CharField(choices=[('Good', 'Good'), ('Damaged', 'Damaged'), (
                'Frozen', 'Frozen')], default='Good', max_length=10),
        ),
        migrations.AlterField(
            model_name='goodsmovement',
            name='item',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='goodsmovement',
            name='sender',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
