# Generated by Django 4.1.3 on 2022-12-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_admin', '0007_goodsmovement_batch_goodsmovement_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcard',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
