# Generated by Django 4.1.3 on 2023-01-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_admin', '0008_itemcard_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcard',
            name='transforming_to_stock',
            field=models.SmallIntegerField(default=0),
        ),
    ]
