# Generated by Django 4.1.3 on 2023-02-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_admin', '0009_itemcard_transforming_to_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamagedGoodsHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('item', models.CharField(max_length=30)),
                ('batch', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('received_from', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
