# Generated by Django 4.1.3 on 2023-02-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_admin', '0011_alter_retailitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='is_retail_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='retail_child_of',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
