# Generated by Django 4.1.3 on 2022-12-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='access_type',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], db_column='access_type', default=0, editable=False, max_length=1),
        ),
    ]
