# Generated by Django 4.1.3 on 2022-12-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_parameter_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='access_type',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], db_column='access_type', default='0', editable=False, max_length=1),
        ),
    ]
