# Generated by Django 4.1.3 on 2022-12-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_parameter_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='parameter_type',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], db_column='parameter_type', default='0', editable=False, max_length=1),
        ),
    ]
