# Generated by Django 4.1.3 on 2022-12-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_parameter_parameter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='parameter_type',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], db_column='parameter_type', default='0', editable=False, max_length=1),
        ),
    ]
